{"name": "test_create_duplicate_comment", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../testdata/create_comment.json'", "trace": "@pytest.mark.negative\n    def test_create_duplicate_comment():\n>       file = open('../testdata/create_comment.json', \"r\")\nE       FileNotFoundError: [Errno 2] No such file or directory: '../testdata/create_comment.json'\n\ntests\\test_create_comment.py:52: FileNotFoundError"}, "start": 1659564911326, "stop": 1659564911327, "uuid": "949d5486-da9e-4717-9089-424deab412b6", "historyId": "d3fe4e10c9d8e579cb23ce965cc59bfd", "testCaseId": "754d4f5b1f0fdadf880a3d9cdd0b4033", "fullName": "tests.test_create_comment#test_create_duplicate_comment", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_comment"}, {"name": "host", "value": "LAPTOP-PKT7OBP8"}, {"name": "thread", "value": "17356-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_comment"}]}